spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path:
    - classpath:/templates
  application:
    name: @artifactId@
  redis:
      port: 7979
      database: 0
      host: 127.0.0.1
      password:
      jedis:
        pool:
          max-active: 1000
          max-wait: -1
          min-idle: 1
          max-idle: 100
#FeginClient：同名service_id无法在注册中心再次注册
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
     defaultZone: http://127.0.0.1:8761/eureka
server:
  port: 80
